/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file profiler.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Code that profiles IntegerLab.
 *
 ******************************************************************************/

/*
 * IntegerLab (c) 2018-23 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include "profiler.h"

void __cyg_profile_func_enter(void *, void *) __attribute__ ((no_instrument_function)); // NOLINT(bugprone-reserved-identifier)
void __cyg_profile_func_exit(void *, void *) __attribute__ ((no_instrument_function)); // NOLINT(bugprone-reserved-identifier)
static int get_function_index(const void *) __attribute__ ((no_instrument_function));

enum function_indices {
    ONE_BIT_FULL_ADDITION = 0,
    RIPPLE_CARRY_ADDITION,
    MULTIPLY_BY_POWER_OF_TWO,
    ADD,
    SUBTRACT,
    UNSIGNED_MULTIPLY,
    UNSIGNED_DIVIDE,
    NUMBER_OF_FUNCTIONS
};

static int call_counts[NUMBER_OF_FUNCTIONS];

static int get_function_index(const void *function_address) {
    if (function_address == one_bit_full_addition) {
        return ONE_BIT_FULL_ADDITION;
    } else if (function_address == ripple_carry_addition) {
        return RIPPLE_CARRY_ADDITION;
    } else if (function_address == multiply_by_power_of_two) {
        return MULTIPLY_BY_POWER_OF_TWO;
    } else if (function_address == add) {
        return ADD;
    } else if (function_address == subtract) {
        return SUBTRACT;
    } else if (function_address == unsigned_multiply) {
        return UNSIGNED_MULTIPLY;
    } else if (function_address == unsigned_divide) {
        return UNSIGNED_DIVIDE;
    } else {
        return -1;
    }
}

void reset_call_counts(void) {
    for (int i = 0; i < NUMBER_OF_FUNCTIONS; i++) {
        call_counts[i] = 0;
    }
}

int get_call_counts(const void *function_address) {
    int function_index = get_function_index(function_address);
    if (function_index >= 0) {
        return call_counts[function_index];
    } else {
        return -1;
    }
}

void __cyg_profile_func_enter(void *function_address, void *call_site) {
    int function_index = get_function_index(function_address);
    if (function_index >= 0) {
        call_counts[function_index]++;
    }
}

void __cyg_profile_func_exit(void *function_address, void *call_site) {}
